[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.variants.design]
capital-b = "more-asymmetric-serifless"
f = "flat-hook-serifless"
m = "short-leg-serifless"
two = "straight-neck-serifless"
three = "two-arcs"
four = "closed-serifless"
five = "oblique-flat-serifless"
asterisk = "penta-mid"
paren = "normal"
brace = "straight"
at = "threefold"
percent = "rings-continuous-slash"
question = "smooth"

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
