MOUSE_BTN3 seek 1 exact
MOUSE_BTN4 seek -1 exact
# does not work
# https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L195
#Ctrl+] sub-scale +0.1
#Ctrl+[ sub-scale -0.1
#Ctrl+] sub-font-size +1
#Ctrl+[ sub-font-size -1

h cycle-values sub-pos "5" "100" ; cycle-values secondary-sub-pos "13" "85"

## Does not work to bind directly
#MBTN_RIGHT       script-binding select/context-menu
#MOUSE_BTN2       script-binding select/context-menu
ctrl+alt+shift+m  script-binding select/menu
MBTN_RIGHT        keypress ctrl+alt+shift+m