# https://raw.githubusercontent.com/mpv-player/mpv/master/etc/input.conf

# Need to ignore first to make it work. Otherwise it seeks more than 1 sec
WHEEL_DOWN ignore
WHEEL_UP ignore
WHEEL_DOWN seek 1 exact
WHEEL_UP seek -1 exact

# does not work
# https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L195
#Ctrl+] sub-scale +0.1
#Ctrl+[ sub-scale -0.1
#Ctrl+] sub-font-size +1
#Ctrl+[ sub-font-size -1

h cycle-values sub-pos "5" "100" ; cycle-values secondary-sub-pos "13" "85"

MBTN_RIGHT  script-binding select/menu
