MOUSE_BTN3 seek 1 exact
MOUSE_BTN4 seek -1 exact
# does not work
# https://github.com/mpv-player/mpv/blob/master/etc/input.conf#L195
#Ctrl+] sub-scale +0.1
#Ctrl+[ sub-scale -0.1
#Ctrl+] sub-font-size +1
#Ctrl+[ sub-font-size -1

#h cycle-values sub-align-y "top" "bottom"
#h cycle-values sub-align-y "top" "bottom" ; cycle-profile "subs-top" ""
#h cycle-profile "subs-top" "subs-bottom"
#h cycle-values sub-align-y "top" "bottom" ; cycle-values sub-pos "0" "100" ; cycle-values secondary-sub-align-y "top" "bottom" ; cycle-values secondary-sub-pos "15" "85"
#h cycle-values sub-align-y "top" "bottom" ; cycle-values sub-pos "0" "100" ; cycle-values secondary-sub-align-y "top" "bottom" ; cycle-values secondary-sub-pos "20" "85"
#h cycle-values sub-pos "15" "100" ; cycle-values secondary-sub-pos "25" "85"
h cycle-values sub-pos "5" "100" ; cycle-values secondary-sub-pos "13" "85"



