#!/bin/bash

history -a ${HISTFILE}.$$
history -c
history -r  # load common history file
# load histories of other sessions
for f in `ls ${HISTFILE}.[0-9]* 2>/dev/null | grep -v "${HISTFILE}.$$\$"`; do
  history -r $f
done
history -r "${HISTFILE}.$$"  # load current session history