#!/bin/bash

# https://stackoverflow.com/questions/55186799/multi-process-bash-within-fzf-preview-feature
#echo '--theme="ansi-light"' >> $(bat --config-file)
SC="$(dirname "$0")"
rg . -n --with-filename "$@" | fzf --preview="source '$SC/string2arg.sh'; string2arg {}"
