#!/usr/bin/env bash
# Commit everything (message = list of changed files), rebase on upstream, push.
set -euo pipefail

git add -A
if ! git diff --cached --quiet; then
	# https://unix.stackexchange.com/questions/114244/replace-all-newlines-to-space-except-the-last/114281#114281
	git commit -m "$(git diff --name-only --staged | perl -p00e 's/\n(?!\Z)/, /g')"
fi
git pull --rebase
git push
