#!/bin/bash
set -e

NAME="$(basename "$PWD")"
PARENT="$(dirname "$PWD")"

GIT_BRANCH_NAME=$1
if [ -n "$GIT_BRANCH_NAME" ]; then
	echo "GIT_BRANCH_NAME is set: _${GIT_BRANCH_NAME}_"
	git putback "$GIT_BRANCH_NAME"
fi

git archive \
	--format=zip \
	--prefix="${NAME}/" \
	-o "$PARENT/${NAME}.zip" \
	HEAD
