#!/bin/bash

FILE_OR_DIR="$1"

if [ -d "$FILE_OR_DIR" ]; then
	pushd "$FILE_OR_DIR"
	FILE_OR_DIR="$(command ls -1tr | tail -1)"
	echo "FILE_OR_DIR=$FILE_OR_DIR"
else
	pushd "$(dirname "$FILE_OR_DIR")"
fi

# pipx install mlx_whisper
mlx_whisper \
	--language en \
	--model mlx-community/whisper-large-v3-mlx \
	--condition-on-previous-text False \
	--word-timestamps True \
	--hallucination-silence-threshold 2 \
	--output-format vtt "$FILE_OR_DIR"
