#!/bin/bash

set -euo pipefail

INPUT="$1"

if [ -d "$INPUT" ]; then
	pushd "$INPUT" >/dev/null
	FILE="$(command ls -1tr | tail -1)"
	echo "FILE=$FILE"
else
	FILE="$(basename "$INPUT")"
	pushd "$(dirname "$INPUT")" >/dev/null
fi

uvx --from mlx-whisper mlx_whisper \
	--language en \
	--model mlx-community/whisper-large-v3-mlx \
	--condition-on-previous-text False \
	--word-timestamps True \
	--hallucination-silence-threshold 2 \
	--output-format vtt \
	"$FILE"
