#!/bin/bash

# pipx install mlx_whisper
mlx_whisper \
	--language en \
	--model mlx-community/whisper-large-v3-mlx \
	--condition-on-previous-text False \
	--word-timestamps True \
	--hallucination-silence-threshold 2 \
	--output-format vtt "$@"
