#!/bin/bash

# TODO: The problem with this solution: when there is some other problem than no subs in this language,
# It will still download them.
# ERROR: Unable to download video subtitles for 'en': HTTP Error 429: Too Many Requests
#yt-dlp --sub-langs en "$1" || yt-dlp --sub-langs pl "$1" || yt-dlp --no-write-subs --no-write-auto-subs "$1"
y --yes-playlist "$@"
