#!/bin/bash

file="$1"
# https://stackoverflow.com/questions/12152626/how-can-i-remove-the-extension-of-a-filename-in-a-shell-script/32584935#32584935
ext="$(echo "$file" | rev | cut -f 2- -d '.' | rev)"
name="$(basename ${package} ${ext})"


ffmpeg -i "$file" "${name}.mp4"
